---
- hosts: all
  remote_user: root
  become: yes
  become_method: su
  tasks:
    - name: "disable selinux"
      shell: "/vagrant/install/selinux-disable.sh"
    - name: yum install epel
      yum: name=epel-release.noarch state=latest
    - name: download remi repo rpm
      get_url: url=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm dest=/root/
    - name: install remi repo rpm
      yum: name=/root/remi-release-7.rpm state=present
    - name: "install packages"
      yum: enablerepo=remi,remi-php56 name={{ item }} state=present
      with_items:
        - ntp
        - libselinux-python
        - inotify-tools
        - libnotify
        - git
        - sudo
        - nginx
        - openssl-perl
        - postgresql
        - postgresql-server
        - postgresql-contrib
        - postgresql-libs
        - graphviz
        - php
        - php-cli
        - php-fpm
        - php-common
        - php-intl
        - php-ldap
        - php-pdo
        - php-pear
        - php-pgsql
        - php-pecl-apcu
        - php-pecl-zendopcache
        - php-process
        - php-pecl-imagick
        - php-gd
        - php-pecl-igbinary
        - php-mbstring
        - php-pecl-redis
        - php-soap
        - php-tidy
        - php-xml
        - php-xmlrpc
        - php-pecl-xattr
        - php-zip
        - php-devel
        - php-mysql
        - gcc
        - libtool
    - name: "add groups"
      group: name=apache state=present
    - name: "add users"
      user: name=apache state=present groups=apache shell=/sbin/nologin home=/var/www
    - name: "initialising postgresql"
      shell: "postgresql-setup initdb"
    - name: "installing phalconphp"
      shell: "/vagrant/install/phalcon.sh"
    - name: "stopping services"
      service: name={{ item }} enabled=no state=stopped
      with_items:
          - "httpd"
    - name: "starting services"
      service: name={{ item }} enabled=yes state=restarted
      with_items:
          - "postgresql"
          - "nginx"
          - "php-fpm"
...
